version : '3'
services:
  # springboot 项目
  boot-project:
    environment:
        TZ: Asia/Shanghai
        LANG: en_US.UTF-8
        LANGUAGE: en_US:en
        LC_ALL: en_US.UTF-8
    build: .
    ports:
      - "8063:8080"
    

  
  